### ISSUE TITLE
It does not work anymore.

### ISSUE THREAD

**Issue by Coherent5845** [sumithemmadi/truecaller-on-termux#2]
Hey, i have installed everything but whenever i recieve a call it does not shows the caller id, i have attached some screenshot below for more details.
![photo_2022-08-07_01-56-39](https://user-images.githubusercontent.com/23115256/183265057-aed0a907-6c21-479a-b973-96bef514b50b.jpg)

Does not show any info about the unknown caller.

![photo_2022-08-07_02-00-15](https://user-images.githubusercontent.com/23115256/183265157-220b333f-4e1b-4c29-bc02-9a40898e6fcd.jpg)

While on manual search it does shows all the info.
![image](https://user-images.githubusercontent.com/23115256/183265376-16f7054b-ec05-4dba-b65d-5deaef2e961b.png)

I have disabled battery optimization on both termux and termux api, i have restarted truecallerjs multiple times and installed "truecaller-on-termux" from scratch multiple times too, but still it wont work.
Please do help me.

**Comment by sumithemmadi** [comment]
hi @hackevil ,

Actually my script only reads notification from Google Dialer which has package name as `com.google.android.dialer` but your phone has  different which has different package name, so thats why it is not working.

Follow the steps below.
- Uninstall truecaller-on-termux
- To uninstall 
```bash
make uninstall
```
- Then stop service with below command
```
sv down truecallerjs
sv-disable truecallerjs
```
- Find default dialer app's package name  to do that just call someone from your phone.
- while you are on call run `termux-notification-list`  and can see a json of all notifications on your phone.
- Just copy the package name of dialer app.
![image](https://user-images.githubusercontent.com/50250422/183287835-37f3ed31-8e67-4db3-bc13-422aa877b964.png)
-  Now export  the exvironment variable DEFAULT_DIALER_APP="Yor Dialer App Package Name" .
-  [click here](https://support.google.com/admob/answer/9972781?hl=en) to know about package name
```bash
export DEFAULT_DIALER_APP="Yor Dialer App Package Name"
```

Example 1: If you use MI Dialer which has a package name `com.android.incalleriu`.
```bash
~$ export DEFAULT_DIALER_APP="com.android.incalleriu"
```
Now install Truecaller-on-termux and run service

**Comment by sumithemmadi** [comment]
this issue is fixes
