### ISSUE TITLE
Getting some problems

### ISSUE THREAD

**Issue by Arnab-Afk** [sumithemmadi/truecaller-on-termux#3]
I have tried this but I am getting some problems. 
When I try to login it shows error 404 but also shows installation successfull hence having doubt there. 
After that when I try to start the start-truecallerjs.sh file through the command $ bash start-truecallerjs.sh 
There is no response or nothing happens after this. 
Even after this I tried the two commands 
$sv-enable truecallerjs
$ sv up truecallerjs

![Screenshot_2023-02-22-00-06-56-997_com termux](https://user-images.githubusercontent.com/69982915/220430676-11606508-5fdc-4bfe-807e-17cc95f94dae.png)
 

My $ termux-notification-list is working fine and showing me package names and I too have Google dialer in Android 12 so there's no problem in the dialer one please help me solving the problem.

**Comment by sumithemmadi** [comment]
Use this https://github.com/sumithemmadi/truecaller-on-termux/releases/tag/v1.0.6 

If it is not working. reply to this comment, I will resolve your issue

**Comment by Arnab-Afk** [comment]
> Use this https://github.com/sumithemmadi/truecaller-on-termux/releases/tag/v1.0.6
> 
> If it is not working. reply to this comment, I will resolve your issue

But how to use those zip files if you can explain. I contacted you in Instagram.

**Comment by sumithemmadi** [comment]
download the zip file unzip it in the termux go to unzipped place and you will see readme file. follow that readme file

**Comment by Arnab-Afk** [comment]
Ok trying it

**Comment by Arnab-Afk** [comment]
> download the zip file unzip it in the termux go to unzipped place and you will see readme file. follow that readme file

![Screenshot_2023-02-22-10-44-05-157_com termux](https://user-images.githubusercontent.com/69982915/220532720-1321a21a-0a9c-455a-bfbc-9281220cc325.png)
That's the outcome

![Screenshot_2023-02-22-11-05-57-366_com miui securitycenter](https://user-images.githubusercontent.com/69982915/220532764-77ddba06-d0d4-49ee-b548-640aa2259bee.png)
![Screenshot_2023-02-22-11-06-26-392_com android settings](https://user-images.githubusercontent.com/69982915/220532787-999639ef-a083-490b-9bc0-d5c94db26b80.png)


I think that's not my cup of tea. 🥲

**Comment by sumithemmadi** [comment]
Your issue is fixed but only work for Google dialer

**Comment by 1114saikrishna** [comment]
I want full comands can u any one give me
