### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by ashrry** [sumithemmadi/truecaller-on-termux#7]
~/truecaller-on-termux $ make install
pkg i nodejs jq termux-api termux-services -y
Checking availability of current mirror:
[*] https://grimler.se/termux/termux-main: ok
Hit:1 https://grimler.se/termux/termux-main stable InRelease
Hit:2 https://grimler.se/termux/termux-x11 x11 InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nodejs is already the newest version (20.2.0-1).
jq is already the newest version (1.7).
termux-api is already the newest version (0.58.0-1).
termux-services is already the newest version (0.13-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /data/data/com.termux/files/usr/lib/node_modules/truecallerjs
npm ERR! dest /data/data/com.termux/files/usr/lib/node_modules/.truecallerjs-RHdQhyB7
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/data/data/com.termux/files/usr/lib/node_modules/truecallerjs' -> '/data/data/com.termux/files/usr/lib/node_modules/.truecallerjs-RHdQhyB7'

npm ERR! A complete log of this run can be found in: /data/data/com.termux/files/home/.npm/_logs/2024-01-20T12_49_27_916Z-debug-0.log
make: *** [Makefile:6: install] Error 217
![Screenshot_2024-01-20-18-23-33-192_com termux](https://github.com/sumithemmadi/truecaller-on-termux/assets/51499053/14a7869f-060e-467d-815e-75a230023bcc)

**Comment by sumithemmadi** [comment]
```sh
mv '/data/data/com.termux/files/usr/lib/node_modules/truecallerjs' '/data/data/com.termux/files/usr/lib/node_modules/.truecallerjs-RHdQhyB7'
```

run this and try again

**Comment by ashrry** [comment]
![Screenshot_2024-01-23-10-58-30-883_com termux](https://github.com/sumithemmadi/truecaller-on-termux/assets/51499053/c721c5a3-7687-4b7e-a46c-57b711ef0016)

**Comment by ashrry** [comment]
can't move
